@extends("layouts.bootstrap")
@section("title","Event Detail")
@section("content")
<h2>Event {{ $detectionEvent->event_type }} <span class="badge bg-danger">{{ $detectionEvent->event_type }}</span></h2>
<div class="row g-3">
    <div class="col-md-4"><div class="card p-3"><h5>Machine Observation</h5><p>Track: <span class="badge bg-dark">ID:{{ $detectionEvent->temporary_track_id }}</span></p><p>Type: {{ $detectionEvent->event_type }}</p><p>Status: <span class="badge bg-info">{{ $detectionEvent->event_status }}</span></p><p>Confidence: {{ $detectionEvent->confidence ?? "—" }} <span class="badge bg-secondary">text+color</span></p><p>Frames: {{ $detectionEvent->started_at_frame }} - {{ $detectionEvent->ended_at_frame }}</p><p>Seconds: {{ $detectionEvent->started_at_seconds }} - {{ $detectionEvent->ended_at_seconds }}</p></div></div>
    <div class="col-md-4"><div class="card p-3"><h5>Supporting Detector/Rule Evidence</h5><p>Model: {{ $detectionEvent->model_version_id }}</p><p>Rule Score: {{ $detectionEvent->rule_score ?? "—" }}</p><p>Evidence: @if($detectionEvent->evidence_available)<span class="badge bg-success">Available</span> @else<span class="badge bg-secondary">Not yet</span>@endif</p><p><strong>Machine observation only - not proof of misconduct.</strong></p>@if($detectionEvent->evidences->isNotEmpty())<ul>@foreach($detectionEvent->evidences as $ev)<li><a href="{{ route("evidence.show",$ev) }}">Evidence {{ $ev->id }} ({{ $ev->file_type }})</a> - not in public directory</li>@endforeach</ul>@endif</div></div>
    <div class="col-md-4"><div class="card p-3"><h5>Human Decision</h5><p>Review Status: <span class="badge @if($detectionEvent->review_status=="pending") bg-warning text-dark @else bg-success @endif">{{ $detectionEvent->review_status }}</span></p><p>Reviewer: {{ $detectionEvent->reviewed_by ?? "—" }}</p><p>Note: {{ $detectionEvent->reviewer_note ?? "—" }}</p><form method="POST" action="{{ route("detection-events.review",$detectionEvent) }}">@csrf<div class="mb-2"><select name="decision" class="form-select" required><option value="confirmed_suspicious">confirmed_suspicious</option><option value="dismissed_normal">dismissed_normal</option><option value="needs_further_review">needs_further_review</option></select></div><div class="mb-2"><input type="text" name="note" class="form-control" placeholder="Note"></div><button class="btn btn-primary btn-sm">Submit Review</button></form></div></div>
</div>
<div class="card p-3 mt-3"><h5>Audit History</h5><p class="text-muted">All review decisions are append-only and audited. Check audit logs for full history.</p><a href="{{ route("audit-logs.index") }}" class="btn btn-outline-secondary btn-sm">View Audit Logs</a></div>
@endsection
